apiVersion: v1
kind: Service
metadata:
  name: invitation-db
  namespace: pcpi
spec:
  selector:
    app: invitation-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: invitation-db
  namespace: pcpi
spec:
  serviceName: invitation-db
  replicas: 1
  selector:
    matchLabels:
      app: invitation-db
  template:
    metadata:
      labels:
        app: invitation-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: invitation_service
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pcpi-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pcpi-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: invitation-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: invitation-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
