syntax = "proto3";

import "google/protobuf/struct.proto";

package notification;

service NotificationService {
  rpc SendEmail (SendEmailRequest) returns (SendEmailResponse);
}

message SendEmailRequest {
  string to = 1;
  EmailTemplate template = 2;
  google.protobuf.Struct params = 3; // parameters in JSON-format
}

message SendEmailResponse {
  bool success = 1;
}

enum EmailTemplate {
  PROJECT_SUBMITTED = 0;
  PROJECT_APPROVED = 1;
  PROJECT_REJECTED = 2;
  JUROR_INVITATION = 3;
  PASSWORD_CHANGED = 4;
  PLATFORM_INVITATION = 5;
  PASSWORD_RESET = 6;
  SIGNUP_CONFIRMATION = 7;
  REQUEST_CHANGES = 8;
  PARTICIPANTS_SUBMITTED = 9; // For competitions
  PARTICIPANTS_APPROVED = 10;
  PARTICIPANTS_REJECTED = 11;
}
