apiVersion: v1
kind: ConfigMap
metadata:
  name: pcpi-config
  namespace: pcpi
data:
  # Common
  NODE_ENV: "development"

  # Database configurations
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"

  # Auth Service
  AUTH_DATABASE_URL: "postgresql://postgres:postgres@auth-db:5432/auth_service"
  AUTH_GRPC_HOST: "0.0.0.0"
  AUTH_GRPC_PORT: "50051"
  JWT_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3d5ZVhsRVRaSW9CdGQKU0dQc3QvUVRHNXBJZWZqcEhRWDBNOEJTcWRnV3ZLWkQraXhrZHhSK1VCcE5hdmpVVEN0ZlNkUnhQWjloVnBJZgpNbTBOZmZkR0paTWN0MkJYa0t4WHY0eXB5Kzd3a3RsM3QxTU1vK0V6UHVTK0ZDUytrWVdpL3djcmNRMVQ5Y0hlCmFKUDlzK1ZtNU03WmFUQmt4bUUzQzRkWFZzYmk1MTFnVkFlRzNIbXVaYjYyMEd6Ui9lcmVQUWk2NEJpeUQ4dmYKQ2U5eS9pNEhCVWlmRDNBKzdUMHRZS3lQT29GalNidmdiSzZhSFlQNmNhN1dNd1dBdzc2bzJDWm52QmNXWCthdgpzdEg2Zk5UbERSWGQ2ZGUwVWhlMzZDR3BiYXhjNlJWY2l0WVRFTFB5bGswZll3VXI1d0xmQlI3M21KTC9EWlB5CmxGKzhLS2sxQWdNQkFBRUNnZ0VBRytqOEFQSjdNZk1JN3V5dlRkOXF5cHQ0ZTRtNkdMOXF3YmRyM1FFUWF1S0UKazBYTFBWOHBYcG14MVZnV2labXUzVC9RS01LVVIyODk2V3Z5R0llekFxR0svS1Vjc2laV2R4SDRHSlJvR0JYdQovRDMyZ0EvZFRWUllFNFFsbXVwcGdTYW5FSjRyL3YzVkNoSlRqdUdZVFdyQkYwVEtqWlplSWEwUnhHR2dTNUQ5CkRhU3FDZGxiSmQ1bTltSTNNV3lXNlBpTGZ0ZU5uWlZBMllKVlR0RjZOOE5sRzZpb2ZoWFpYS1BKaFlBekJFRFUKVG1vY3FQN280M1I4TVFTamIxQ1JZc1l5U0xibndhOGZRSkRPcWdjcUV5R2ZZWHk2WGM3SEJRVjFTOElPc2lrQQpLRDdiVUMxSE44VGQ4S1VPcC9aUmxGQkFiTXFOS1ZBT0JncWJ0MnIwM3dLQmdRRGREWC9pY3BQd09Yd2ErRHNpCmFBL2VxaFRMbDRrTG1Ld09PTWE0YkNhcVF3bzJkTmVtN1E1UlJEL0lsREhCRGdlQkRtS0RxcGxmVTlhN3pncGkKUHo3QzAwckZ1YzZJWC9BS2JLMm51MVBXd09lS1c5T2UzS1hDVzVqY0hHZmdDbXBzL0FNeXoyeThCa2N4bEdVVworeFlRbFNBb2hPUSt0c0FocnlQZlBvOThad0tCZ1FETXZPNm04TmVUQ2ZZVHRkZzN1c2dydGtlczJwN0JwOGx5CmZMUGx4OHBjODJLSkhTd0VmR0h5bDJtQm0rZlJnWERJR0ZYdGkrQXdVZ0EzcXY2VGk2WC9jMVdPaDU4aTVPNXkKQ1hGSTZDNTRmNjFodzduMTAzbkoxM2VCL2VvcFpoWUpzajM5WUUxNGYwZENUVklsbzNaRGQxQlFzaVVyV1Z0MAphZVlQY05Pc0F3S0JnQUszOWNpdExCQ2FSR0o0aHhHblFmcTFFTWhvTnJGRDBXbmpYTjVMeGpYMTJSeE9WNUNmCi9ic1dJY3F2dCtUdDdUMnpGWmNVOUFudUdBZjdRcmx1bWJEL3REMjJTVW40RkJXc3ZINEJtY2hjV3Z5aW9IbWwKc1F3dzRESmt6d284Vm82OGtyVi9RNUVVYXErN2FYcmMzNnFZaXVxMHA3SDF3V3Nvb2tKT25La2xBb0dCQUlVeApLQ1NzcStHNWFqLzZYZllyYWd1ZDR0VWR5SWY5YXIwelNTbGtKMDcrK3d4dVVQTitJNDVaV0ViOE1QeUhzK0pJCmlxWW1DQ3dIUEtMNmQvRnV1UWdOZFF4clNHaS8vQ3R0M3lmcC9FbGg3bDZhb1VDK1dnMm9RZFBzWnNpVjVDSmMKdFowL2FFYktyb1lBblQ5bEx3dkc5Qlg3UHRrTG9jYURHaXJUWUxFWEFvR0JBSk9PZDJjSVJQL1dSa2UrRTJxeAp5cHh4MlhTMHNYSHI1cW9xekhuMWkvd0dkY29NZzU3RFZ5Uk03TGJDM00vYjBqYkFZYTNLZkRFTGltcHFqMGpnCmtaOVZUaTRSU2NYREYvTVVVRG1PdlhIbWRmeTdib1ExbStWeVo0Q0t4azE4aFJyaW8vN1h2SHJ3T0tGN0hFL3AKV2REL2R1WEl0NWw4WmluZ1Y5bzdHZDIxCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
  JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzTW5sNVJFMlNLQWJYVWhqN0xmMApFeHVhU0huNDZSMEY5RFBBVXFuWUZyeW1RL29zWkhjVWZsQWFUV3I0MUV3clgwblVjVDJmWVZhU0h6SnREWDMzClJpV1RITGRnVjVDc1Y3K01xY3Z1OEpMWmQ3ZFRES1BoTXo3a3ZoUWt2cEdGb3Y4SEszRU5VL1hCM21pVC9iUGwKWnVUTzJXa3daTVpoTnd1SFYxYkc0dWRkWUZRSGh0eDVybVcrdHRCczBmM3EzajBJdXVBWXNnL0wzd252Y3Y0dQpCd1ZJbnc5d1B1MDlMV0NzanpxQlkwbTc0R3l1bWgyRCtuR3Uxak1GZ01PK3FOZ21aN3dYRmwvbXI3TFIrbnpVCjVRMFYzZW5YdEZJWHQrZ2hxVzJzWE9rVlhJcldFeEN6OHBaTkgyTUZLK2NDM3dVZTk1aVMvdzJUOHBSZnZDaXAKTlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

  # Evaluation Service
  EVALUATION_DATABASE_URL: "postgresql://postgres:postgres@evaluation-db:5432/evaluation_service"
  EVALUATION_GRPC_HOST: "0.0.0.0"
  EVALUATION_GRPC_PORT: "50052"

  # Event Service
  EVENT_DATABASE_URL: "postgresql://postgres:postgres@event-db:5432/event_service"
  EVENT_GRPC_HOST: "0.0.0.0"
  EVENT_GRPC_PORT: "50053"

  # Invitation Service
  INVITATION_DATABASE_URL: "postgresql://postgres:postgres@invitation-db:5432/invitation_service"
  INVITATION_GRPC_HOST: "0.0.0.0"
  INVITATION_GRPC_PORT: "50054"

  # Project Service
  PROJECT_DATABASE_URL: "postgresql://postgres:postgres@project-db:5432/project_service"
  PROJECT_GRPC_HOST: "0.0.0.0"
  PROJECT_GRPC_PORT: "50055"

  # Gateway Service URLs
  AUTH_SERVICE_URL: "auth-service:50051"
  EVALUATION_SERVICE_URL: "evaluation-service:50052"
  EVENT_SERVICE_URL: "event-service:50053"
  INVITATION_SERVICE_URL: "invitation-service:50054"
  PROJECT_SERVICE_URL: "project-service:50055"

  # Notification Service
  EMAIL_PUBLIC_KEY: "JSamv4icvDDEi6eMZ"
  EMAIL_PRIVATE_KEY: "v2Pi81dRQn5520f8mWlq8"
  EMAILJS_TEMPLATE_PROJECT-CONFIRMATION_ID: "template_mqar2l3"
