name: Docker Image CI

on:
  pull_request:
    branches: [ "dev", "prod" ]
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch target (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:

  search-individual-migration-service-changes:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
      coolify-url: ${{ steps.obtain-coolify-url-token.outputs.coolify_url }}
      coolify-token: ${{ steps.obtain-coolify-url-token.outputs.coolify_token }}
      branch: ${{ steps.obtain-coolify-url-token.outputs.branch }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Obtain boolean about changed file
        uses: dorny/paths-filter@v4
        id: filter
        with:
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.before }}
          filters: |
            auth-service:
              - 'apps/auth-service/**'
            evaluation-service:
              - 'apps/evaluation-service/**'
            event-service:
              - 'apps/event-service/**'
            invitation-service:
              - 'apps/invitation-service/**'
            project-service:
              - 'apps/project-service/**'
            notification-service:
              - 'apps/notification-service/**'
            gateway:
              - 'apps/gateway/**'
      
      - name: Obtain Coolify Url and Token
        id: obtain-coolify-url-token
        run: |
          BRANCH="${{ github.event_name == 'workflow_dispatch' && inputs.target_branch || github.base_ref }}"
          echo "branch: $BRANCH"
          COOLIFY_URL=$(echo "$COOLIFY_URLS_TOKENS_JSON" | jq -r ".\"$BRANCH\".url")
          COOLIFY_TOKEN=$(echo "$COOLIFY_URLS_TOKENS_JSON" | jq -r ".\"$BRANCH\".token")

          echo "coolify_url=$COOLIFY_URL" >> $GITHUB_OUTPUT
          echo "coolify_token=$COOLIFY_TOKEN" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        
        env:
          COOLIFY_URLS_TOKENS_JSON: ${{ secrets.COOLIFY_URLS_TOKENS_JSON }}

  migrations-service-build:
    runs-on: ubuntu-24.04-arm
    needs: search-individual-migration-service-changes
    if: ${{ 
      contains(fromJSON(needs.search-individual-migration-service-changes.outputs.services), 'auth-service') ||
      contains(fromJSON(needs.search-individual-migration-service-changes.outputs.services), 'evaluation-service') ||
      contains(fromJSON(needs.search-individual-migration-service-changes.outputs.services), 'event-service') ||
      contains(fromJSON(needs.search-individual-migration-service-changes.outputs.services), 'invitation-service') ||
      contains(fromJSON(needs.search-individual-migration-service-changes.outputs.services), 'project-service')
      }}

    strategy:
      fail-fast: false
      matrix:
        services: ${{ fromJSON(needs.search-individual-migration-service-changes.outputs.services) }}
        exclude:
          - services: notification-service
          - services: gateway
        
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Creation of the SHA tag 
        uses: docker/metadata-action@v5
        id: sha-tag
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: type=sha,prefix=sha-,suffix=-${{ matrix.services }}
    
      - name: Separation of image and tag
        id: image_tag
        run: |
          IMAGE_AND_TAG="${{ steps.sha-tag.outputs.tags }}"
          IMAGE="${IMAGE_AND_TAG%%:*}"
          TAG="${IMAGE_AND_TAG##*:}"
          
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
    
      - name: post dinamic env value
        id: dinamic-env
        run: |
          WEBHOOK_APP_URL=$(echo "$COOLIFY_WEBHOOKS_JSON" | jq -r ".\"${{ needs.search-individual-migration-service-changes.outputs.branch }}\".\"${{ matrix.services }}\".webhook_app_url")
          APP_UUID=$(echo "$COOLIFY_WEBHOOKS_JSON" | jq -r ".\"${{ needs.search-individual-migration-service-changes.outputs.branch }}\".\"${{ matrix.services }}\".app_uuid")
          WEBHOOK_MIGRATION_URL=$(echo "$COOLIFY_WEBHOOKS_JSON" | jq -r ".\"${{ needs.search-individual-migration-service-changes.outputs.branch }}\".\"${{ matrix.services }}\".webhook_migration_url")
          MIGRATION_UUID=$(echo "$COOLIFY_WEBHOOKS_JSON" | jq -r ".\"${{ needs.search-individual-migration-service-changes.outputs.branch }}\".\"${{ matrix.services }}\".migration_uuid")

          echo "webhook_app_url=$WEBHOOK_APP_URL" >> $GITHUB_OUTPUT
          echo "app_uuid=$APP_UUID" >> $GITHUB_OUTPUT
          echo "webhook_migration_url=$WEBHOOK_MIGRATION_URL" >> $GITHUB_OUTPUT
          echo "migration_uuid=$MIGRATION_UUID" >> $GITHUB_OUTPUT

        env:
          COOLIFY_WEBHOOKS_JSON: ${{ secrets.COOLIFY_WEBHOOKS_JSON }}

        
      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/${{ matrix.services }}/Dockerfile 
          tags: ${{ steps.sha-tag.outputs.tags }}
          platforms: linux/arm64
          push: true
          no-cache: true

    
      - name: Set Coolify Migration Tag
        run: |
          curl "https://${{ needs.search-individual-migration-service-changes.outputs.coolify-url }}/api/v1/applications/${{ steps.dinamic-env.outputs.migration_uuid }}" \
          --request PATCH \
          --header "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}" \
          --header "Content-Type: application/json" \
          --data "{
            \"docker_registry_image_name\": \"${{ steps.image_tag.outputs.image }}\",
            \"docker_registry_image_tag\": \"${{ steps.image_tag.outputs.tag }}\"
          }"

      - name: Redeploy Coolify Migration Image
        id: redeploy-and-deploymentID
        run: |
          RESPONSE=$(curl -sS -f \
          --request GET "${{ steps.dinamic-env.outputs.webhook_migration_url }}" \
          --header "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}")

          echo $RESPONSE
          DEPLOYMENT_UUID=$(echo "$RESPONSE" | jq -r ".deployments[0].deployment_uuid")
          echo "deployment_uuid=$DEPLOYMENT_UUID" >> $GITHUB_OUTPUT
    
      - name: Check redeployment status of Coolify Migration Image
        id: check-status-deployment
        run: |
          while true; do
            STATUS=$(curl -s \
              "https://${{ needs.search-individual-migration-service-changes.outputs.coolify-url }}/api/v1/deployments/${{ steps.redeploy-and-deploymentID.outputs.deployment_uuid }}" \
              -H "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}" | jq -r ".status")

            echo $STATUS  
            if [ "$STATUS" = "finished" ]; then
              echo "Deploy exitoso"
              echo "final_status=True" >> $GITHUB_OUTPUT
              exit 0
            elif [ "$STATUS" = "failed" ] || [ "$STATUS" = "error" ]; then
              echo "Deploy falló"
              echo "final_status=False" >> $GITHUB_OUTPUT
              exit 1
            fi

            sleep 5
          done
    
      - name: set coolify application tag
        if: ${{ steps.check-status-deployment.outputs.final_status == 'True' }}
        run: |
          curl "https://${{ needs.search-individual-migration-service-changes.outputs.coolify-url }}/api/v1/applications/${{ steps.dinamic-env.outputs.app_uuid }}" \
          --request PATCH \
          --header "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}" \
          --header "Content-Type: application/json" \
          --data "{
            \"docker_registry_image_name\": \"${{ steps.image_tag.outputs.image }}\",
            \"docker_registry_image_tag\": \"${{ steps.image_tag.outputs.tag }}\"
          }"

      - name: Redeploy Coolify Application Image
        run: |
          curl --request GET "${{ steps.dinamic-env.outputs.webhook_app_url }}" \
          --header "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}"
  
  no-migration-service-build:
    runs-on: ubuntu-24.04-arm
    needs: search-individual-migration-service-changes
    if: ${{ 
      contains(needs.search-individual-migration-service-changes.outputs.services, 'notification-service') || 
      contains(needs.search-individual-migration-service-changes.outputs.services, 'gateway')
        }}

    strategy:
      fail-fast: false
      matrix:
        services: ${{ fromJSON(needs.search-individual-migration-service-changes.outputs.services) }}
        exclude:
          - services: auth-service
          - services: evaluation-service
          - services: event-service
          - services: invitation-service
          - services: project-service

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Creation of the SHA tag 
        uses: docker/metadata-action@v5
        id: sha-tag
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: type=sha,prefix=sha-,suffix=-${{ matrix.services }}
    
      - name: Separation of image and tag
        id: image_tag
        run: |
          IMAGE_AND_TAG="${{ steps.sha-tag.outputs.tags }}"
          IMAGE="${IMAGE_AND_TAG%%:*}"
          TAG="${IMAGE_AND_TAG##*:}"
          
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
    
      - name: post dinamic env value
        id: dinamic-env
        run: |
          WEBHOOK_APP_URL=$(echo "$COOLIFY_WEBHOOKS_JSON" | jq -r ".\"${{ needs.search-individual-migration-service-changes.outputs.branch }}\".\"${{ matrix.services }}\".webhook_app_url")
          APP_UUID=$(echo "$COOLIFY_WEBHOOKS_JSON" | jq -r ".\"${{ needs.search-individual-migration-service-changes.outputs.branch }}\".\"${{ matrix.services }}\".app_uuid")

          echo "webhook_app_url=$WEBHOOK_APP_URL" >> $GITHUB_OUTPUT
          echo "app_uuid=$APP_UUID" >> $GITHUB_OUTPUT

        env:
          COOLIFY_WEBHOOKS_JSON: ${{ secrets.COOLIFY_WEBHOOKS_JSON }}
        
      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/${{ matrix.services }}/Dockerfile 
          tags: ${{ steps.sha-tag.outputs.tags }}
          platforms: linux/arm64
          push: true
          no-cache: true
    
      - name: set coolify Application tag
        run: |
          curl "https://${{ needs.search-individual-migration-service-changes.outputs.coolify-url }}/api/v1/applications/${{ steps.dinamic-env.outputs.app_uuid }}" \
          --request PATCH \
          --header "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}" \
          --header "Content-Type: application/json" \
          --data "{
            \"docker_registry_image_name\": \"${{ steps.image_tag.outputs.image }}\",
            \"docker_registry_image_tag\": \"${{ steps.image_tag.outputs.tag }}\"
          }"

      - name: Redeploy Coolify Application Image
        run: |
          curl --request GET "${{ steps.dinamic-env.outputs.webhook_app_url }}" \
          --header "Authorization: Bearer ${{ needs.search-individual-migration-service-changes.outputs.coolify-token }}"
