name: Docker Image CI

on:
  push:
    branches: [ "refactor/CU-86e0d71ar/Dev-Tooling-Investigate-and-document-Dockerfile-optimization-opportunities" ]
  pull_request:
    branches: [ "prod" , "dev" ]

jobs:
  login-dockerhub:
    runs-on: ubuntu-24.04
    outputs:
      username: ${{ steps.get-username.outputs.username_tag}}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      id: get-username
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "username_tag=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_OUTPUT

  
  migrations-service-build:
    needs: login-dockerhub
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        services: [auth,evaluation,event,invitation,project,notification,gateway]
        
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Creation of the SHA tag 
      uses: docker/metadata-action@v5
      id: sha-tag
      with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/${{ matrix.services }}
          tags: type=sha,prefix=sha-
        
    - name: Build and push base image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ needs.login-dockerhub.outputs.username }}/${{ steps.sha-tag.outputs.tags }}
        push: true

    
    
    
    
