services:
  postgres:
    image: postgres:15-alpine
    container_name: evaluation-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: evaluationsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evaluation-network

volumes:
  postgres_data:

networks:
  evaluation-network:
    driver: bridge
